/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "DonateAletheiaApi",
            "endpoint": "https://xvtra0b6xg.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        },
        {
            "name": "PaymentAletheiaApi",
            "endpoint": "https://upzeo4uece.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
